# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd7a448fda9ff9181b2a06849047357d7b9966a7aeaa0b933e3799b87f0cc5fa1e71177165749be312adffeae1ea54338e66b9b788aa6276771e15de93b64d3

test:
  secret_key_base: a35f80d6bf66ce51688dfa3570f3099231445cc379c4645ac9c229621aaa35cec8a7b665ce058ad440192a0be8ac7b8dc6b45e0aaa005660e355e68ccec7484f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
